const questions = [
  {topic:'materiel', label:'MATÉRIEL', text:'Quel élément permet de relier un tuyau à une prise d’eau ?', answers:['Un raccord','Une lance','Un dévidoir','Un casque'], correct:0, explain:'Un raccord assure l’assemblage entre les éléments d’une ligne d’eau. Relis la fiche matériel avec ton animateur.'},
  {topic:'incendie', label:'INCENDIE', text:'Le triangle du feu réunit trois éléments. Lequel n’en fait pas partie ?', answers:['Un combustible','Un comburant','Une énergie d’activation','Un point d’eau'], correct:3, explain:'Le triangle du feu associe combustible, comburant et énergie d’activation. Cette fiche sert à comprendre le phénomène du feu.'},
  {topic:'secours', label:'SECOURS À PERSONNE', text:'Lors d’un entraînement JSP, quelle règle reste prioritaire ?', answers:['Aller le plus vite possible','Suivre les consignes de l’encadrant','Finir avant les autres','Utiliser son téléphone'], correct:1, explain:'La sécurité et les consignes de l’encadrement passent toujours avant la vitesse ou le score.'},
  {topic:'organisation', label:'ORGANISATION', text:'Pourquoi une communication claire est-elle importante pendant une manœuvre ?', answers:['Pour faire plus de bruit','Pour coordonner le groupe','Pour gagner des points','Pour impressionner'], correct:1, explain:'Une communication claire aide le groupe à se coordonner pendant les exercices. Les mots et procédures exacts sont appris avec la section.'},
  {topic:'materiel', label:'MATÉRIEL', text:'À quoi sert principalement un dévidoir ?', answers:['À protéger les mains','À transporter et dérouler un tuyau','À éteindre seul un feu','À stocker un casque'], correct:1, explain:'Le dévidoir permet le transport et le déroulement contrôlé de tuyaux. Demande à voir le modèle utilisé dans ta section.'},
  {topic:'incendie', label:'INCENDIE', text:'Une bonne révision d’une notion difficile commence par…', answers:['La mémoriser sans comprendre','Relire une explication fiable','Deviner la réponse','Passer à autre chose'], correct:1, explain:'Comprendre d’abord rend la mémorisation bien plus durable. Utilise ensuite les cartes pour vérifier ce que tu retiens.'}
];
let queue=[...questions], current=0, answered=false, weekly=Number(localStorage.getItem('mm-weekly')||18), streak=Number(localStorage.getItem('mm-streak')||3);
const $=s=>document.querySelector(s);const modal=$('#modal');
function showModal(title,text,icon='✦',action='Compris'){ $('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modalIcon').textContent=icon;$('#modalAction').textContent=action;modal.hidden=false; }
function updateStats(){ $('#weeklyCount').textContent=weekly;$('#streakValue').textContent=`${streak} jours`;$('#dueCount').textContent=Math.max(0,queue.length-current);localStorage.setItem('mm-weekly',weekly);localStorage.setItem('mm-streak',streak); }
function startQuiz(topic='all'){ queue=topic==='all'?[...questions]:questions.filter(q=>q.topic===topic); if(!queue.length) queue=[...questions];current=0;answered=false;$('#quizIntro').hidden=true;$('#quizArea').hidden=false;renderQuestion(); }
function renderQuestion(){ const q=queue[current]; if(!q){ finishQuiz();return;} answered=false;$('#questionPosition').textContent=`Question ${current+1} sur ${queue.length}`;$('#questionTopic').textContent=q.label;$('#questionText').textContent=q.text;$('#quizProgress').style.width=`${((current+1)/queue.length)*100}%`;const answers=$('#answers');answers.innerHTML='';q.answers.forEach((a,i)=>{const button=document.createElement('button');button.className='answer';button.textContent=a;button.onclick=()=>answerQuestion(i);answers.append(button)});$('#feedback').hidden=true;$('#nextQuestion').hidden=true; }
function answerQuestion(index){if(answered)return;answered=true;const q=queue[current];const buttons=[...document.querySelectorAll('.answer')];buttons.forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');if(i===index&&i!==q.correct)b.classList.add('wrong')});const good=index===q.correct;const feedback=$('#feedback');feedback.replaceChildren();const title=document.createElement('b');title.textContent=good?'Bien joué !':'À revoir';feedback.append(title,document.createTextNode(q.explain));feedback.hidden=false;$('#nextQuestion').hidden=false;if(good){weekly++;}updateStats();}
function finishQuiz(){ $('#quizArea').hidden=true;$('#quizIntro').hidden=false;$('#quizIntro').innerHTML=`<span class="quiz-kicker">SÉANCE TERMINÉE</span><h3>Très bon travail.</h3><p>Tu viens de travailler ${queue.length} cartes. Les notions à revoir reviendront au meilleur moment.</p><div class="session-list"><span>✓ Progression enregistrée</span><span>✓ Prochaine révision : demain</span></div><button class="button button-primary" id="restartQuiz">Refaire une séance <span>→</span></button>`;$('#restartQuiz').onclick=()=>startQuiz();streak=Math.min(streak+1,99);updateStats();}
function coachReply(text){const lower=text.toLowerCase();if(lower.includes('question')||lower.includes('interrog'))return 'Question rapide : quel élément ne fait pas partie du triangle du feu ? Réponds dans tes mots, puis je t’aide à vérifier.';if(lower.includes('5 minute')||lower.includes('plan'))return 'Plan de 5 minutes : 1) deux cartes matériel, 2) une question incendie, 3) relis l’explication de ton erreur. Ensuite, arrête-toi : la régularité compte plus que les longues sessions.';if(lower.includes('matériel')||lower.includes('materiel'))return 'Le matériel sert à acheminer et utiliser les moyens nécessaires à une manœuvre. Commence par retenir le rôle de chaque pièce, puis observe-la lors de la prochaine séance. Veux-tu une question sur les raccords ?';if(lower.includes('incend'))return 'Pour le feu, retiens d’abord le triangle : combustible, comburant et énergie d’activation. La partie pratique se travaille uniquement avec ton encadrement.';return 'Je peux t’aider à réviser le matériel, l’incendie, le secours à personne ou l’organisation. Choisis un thème, et je te l’expliquerai simplement à partir de tes fiches.'}
async function sendCoach(text){if(!text.trim())return;const user=document.createElement('div');user.className='chat-bubble user';user.textContent=text;$('#coachChat').append(user);const reply=document.createElement('div');reply.className='chat-bubble bot';reply.textContent='Je cherche dans les fiches validées…';$('#coachChat').append(reply);$('#coachChat').scrollTop=$('#coachChat').scrollHeight;try{const response=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:text})});const data=await response.json();if(response.status===401){reply.textContent='Connecte-toi pour utiliser le Coach Fire Quiz.';return;}if(!response.ok)throw Error(data.error||'Le coach est indisponible.');reply.textContent=data.answer;if(data.sources?.length){const sources=document.createElement('small');sources.textContent=`Sources : ${data.sources.map(s=>s.label).join(', ')}`;reply.append(document.createElement('br'),sources);}}catch{reply.textContent=coachReply(text);}finally{$('#coachChat').scrollTop=$('#coachChat').scrollHeight;}}
$('#startQuiz').onclick=()=>startQuiz();$('#nextQuestion').onclick=()=>{current++;renderQuestion()};$('#quitQuiz').onclick=()=>{ $('#quizArea').hidden=true;$('#quizIntro').hidden=false; };document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>{document.querySelectorAll('.topic').forEach(x=>x.classList.remove('active'));b.classList.add('active');startQuiz(b.dataset.topic)});document.querySelectorAll('.quick-prompts button').forEach(b=>b.onclick=()=>sendCoach(b.dataset.prompt));$('#coachForm').onsubmit=e=>{e.preventDefault();sendCoach($('#coachInput').value);$('#coachInput').value=''};$('#premiumButton').onclick=()=>showModal('Premium arrive bientôt','La version présentée est prête à tester. Pour activer de vrais paiements, un parent ou responsable légal devra créer et relier un compte de paiement sécurisé.','✦','Go !');$('#freeButton').onclick=$('#accountButton').onclick=()=>showModal('Espace de test','Ton espace de démonstration est déjà ouvert : lance simplement une séance. La connexion sera activée avec la version serveur.','✓','Go !');$('#closeModal').onclick=()=>modal.hidden=true;$('#modalAction').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.hidden=true});document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>$('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth'}));$('#year').textContent=new Date().getFullYear();updateStats();
